version: '3.8'

services:
  postgresqldb:
    image: postgres:13
    container_name: db
    profiles:
      - flask
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - ./flask_os/.env
  flask_migrations:
    container_name: migrations
    build: ./flask_os/
    profiles:
      - migrations
      - flask
    volumes:
      - ./flask_os/:/code/
    env_file:
      - ./flask_os/.env
    command: alembic upgrade head     
    depends_on:
      - postgresqldb
  flask:
    build: ./flask_os
    container_name: flask-app
    command: flask run app.py
    restart: always
    profiles:
      - flask
    volumes:
      - ./flask_os/:/code/
    env_file:
      - ./flask_os/.env
    depends_on:
      - postgresqldb
  mongodb:
    image: mongo:4.2.20-rc0
    container_name: mongo
    restart: always
    volumes:
      - _mongodb_data:/var/lib/mongodb/data
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.10.0-rc.1
    container_name: rabbitmq
    restart: always
    volumes:
      - _rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
    env_file:
      - app-fastapi/.env
  fastapi-app:
    build: ./app-fastapi
    container_name: fastapi-app
    restart: always
    volumes:
      - ./app-fastapi:/app
    env_file:
      - app-fastapi/.env
    depends_on:
      - mongodb
      - rabbitmq
  celery:
    build: ./app-fastapi
    container_name: celery
    command: celery -A tasks worker -l info
    volumes:
      - ./app-fastapi:/app
    links:
      - rabbitmq
    depends_on:
      - fastapi-app
  flower:
    build: ./app-fastapi
    container_name: flower
    command: celery flower
    volumes:
      - ./app-fastapi:/app
    ports:
      - 5555:5555
    env_file:
      - app-fastapi/.env
    depends_on:
      - celery
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-app

volumes:
  _rabbitmq_data:
  _mongodb_data:
  _postgres_data:

