version: '3.8'

services:
  postgresqldb:
    image: postgres:13
    container_name: postgresqldb
    profiles:
      - postgresqldb
      - flask
    volumes:
      - _postgres_data:/var/lib/postgresql/data
    env_file:
      - ./flask_os/.env
    ports:
      - 5430:5432
  # flask_migrations:
  #   container_name: migrations
  #   build: ./flask_os/
  #   profiles:
  #     - migrations
  #     - flask
  #   volumes:
  #     - ./flask_os/:/code/
  #   env_file:
  #     - ./flask_os/.env
  #   command: alembic upgrade head
  #   depends_on:
  #     - postgresqldb
  flask:
    build: ./flask_os
    container_name: flask-app 
    command: gunicorn app:app --bind=0.0.0.0:5000 --timeout 120 --reload --log-level=debug
    restart: on-failure:2
    profiles:
      - flask
    volumes:
      - ./flask_os/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./flask_os/.env
    depends_on:
      - postgresqldb
  mongodb:
    image: mongo:4.2.20-rc0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    profiles:
      - mongodb
  rabbitmq:
    image: rabbitmq:3.10.0-rc.1
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
    env_file:
      - .env
    profiles:
      - rabbitmq
  fastapi-app:
    build: ./app-fastapi
    container_name: fastapi-app
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    profiles:
      - fastapi
  celery:
    build:
      context: ./app-fastapi
    container_name: celery
    working_dir: /app/app-fastapi
    command: celery -A tasks worker -l info
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - fastapi-app
    profiles:
      - celery
  flower:
    build: ./app-fastapi
    container_name: flower
    working_dir: /app/app-fastapi
    command: celery flower
    volumes:
      - .:/app
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: ${RABBIT_BROKER}
      CELERY_RESULT_BACKEND: ${RABBIT_BACKEND}
    depends_on:
      - celery
    profiles:
      - flower
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - fastapi-app
    profiles:
      - nginx

volumes:
  static_value:
  media_value:
  _postgres_data:
    